# grpc 配置
grpc:
  host: ""
  port: ":50052"
  name: "user-grpc"

# http 配置
http:
  host: ""
  port: ":9002"
  name: "user-http"

# database config
database:
  mysql:
    host: 172.16.222.36 # Host
    port: 3306 # Port
    username: root # Username
    password: 1100 # Password
    database: rgrpc-user # Database
    charset: utf8mb4 # Charset
    maxIdleCons: 10 # Maximum number of connections in the idle connection pool
    maxOpenCons: 100 # Maximum number of open database connections
    logMode: info # Log level
    enableFileLogWriter: true # Whether to enable log files
    logFilename: sql.log # Log file name

# redis config
redis:
  host: 172.16.222.36
  port: ":6379"
  username: "default"
  password: "1100"
  database: 0
  dial_timeout: 10s
  read_timeout: 10s
  write_timeout: 10s
  pool_timeout: 10s
  pool_size: 10

# client
client:
  # order 客户端配置
  orderHost: order
  orderPort: ":50051"
  # product 客户端配置
  productHost: product
  productPort: ":50051"

# tracer
trace:
  tracerName: "user-service-tracer"
  serviceName: "user-service"
  endPoint: "otel-collector.otel:4317"