// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/janrs-io/Jgrpc-otel-span"
	"productservice/config"
	"productservice/service/v1/server"
)

// Injectors from wire.go:

func InitServer(cfg string) (*Server, error) {
	configConfig := config.NewConfig(cfg)
	group := NewRunGroup()
	logger := NewLogger()
	server := NewHttpServer(configConfig)
	db := NewMysqlDB(configConfig)
	tracerProvider, err := NewTrace(configConfig)
	if err != nil {
		return nil, err
	}
	otelSpan := Jgrpc_otelspan.New(tracerProvider)
	repository := serverV1.NewRepository(db, configConfig, otelSpan)
	productServiceServer := serverV1.NewServer(logger, repository)
	grpcServer := NewGrpcServer(productServiceServer)
	serverServer := NewServer(configConfig, group, logger, server, grpcServer, db, repository, tracerProvider)
	return serverServer, nil
}
