// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"productservice/config"
	"productservice/service/v1/client"
	"productservice/service/v1/server"
)

// Injectors from wire.go:

func InitServer(cfg string) (*Server, error) {
	configConfig := config.NewConfig(cfg)
	group := NewRunGroup()
	logger := NewLogger()
	server := NewHttpServer(configConfig)
	db := NewDB(configConfig)
	repository := serverV1.NewRepository(db)
	authServiceClient, err := clientV1.NewAuthClient(configConfig)
	if err != nil {
		return nil, err
	}
	productServiceServer := serverV1.NewServer(logger, repository, authServiceClient)
	grpcServer := NewGrpcServer(logger, productServiceServer)
	serverServer := NewServer(configConfig, group, logger, server, grpcServer, db, repository)
	return serverServer, nil
}
