apiVersion: v1
kind: Service
metadata:
  name: dtm-svc
  namespace: dtm-prod
  labels:
    app: dtm
spec:
  ports:
    - port: 36790
      targetPort: 36790
      name: grpc
      appProtocol: grpc # Kubernetes v1.20 [stable]，低版本请剔除此行
    - port: 36789
      targetPort: 36789
      name: http
      appProtocol: http # Kubernetes v1.20 [stable]，低版本请剔除此行
  selector:
    app: dtm
  type: ClusterIP