// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"authservice/config"
	"authservice/service/v1/client"
	"authservice/service/v1/server"
)

// Injectors from wire.go:

func InitServer(cfg string) (*Server, error) {
	configConfig := config.NewConfig(cfg)
	client := NewRedis(configConfig)
	repository := serverV1.NewRepository(client)
	group := NewRunGroup()
	logger := NewLogger()
	server := NewHttpServer(configConfig)
	authServiceClient, err := clientV1.NewAuthClient(configConfig)
	if err != nil {
		return nil, err
	}
	authServiceServer := serverV1.NewServer(repository, authServiceClient)
	grpcServer := NewGrpcServer(logger, authServiceServer)
	serverServer := NewServer(repository, configConfig, group, logger, server, grpcServer)
	return serverServer, nil
}
