# grpc 服务配置
grpc:
  host: ""
  port: ":50051"
  name: "order-grpc"

# http 服务配置
http:
  host: ""
  port: ":9001"
  name: "order-http"

# database 数据库配置
database:
  mysql:
    host: 192.168.1.36 # Host
    port: 3306 # Port
    username: john # Username
    password: 123456 # Password
    database: rgrpc-order # Database
    charset: utf8mb4 # Charset
    maxIdleCons: 10 # Maximum number of connections in the idle connection pool
    maxOpenCons: 100 # Maximum number of open database connections
    logMode: info # Log level
    enableFileLogWriter: true # Whether to enable log files
    logFilename: sql.log # Log file name

# redis 配置
redis:
  host: 192.168.1.36
  port: ":6379"
  username: "default"
  password: "123456"
  database: 0
  dial_timeout: 10s
  read_timeout: 10s
  write_timeout: 10s
  pool_timeout: 10s
  pool_size: 10

# client 客户端配置
client:
  # product 产品服务客户端
  productHost: product
  productPort: ":50051"

# otel trace 链路追踪配置
trace:
  tracerName: "order-service-tracer"
  serviceName: "order-service"
  endPoint: "otel-collector.otel:4317"