# http service
apiVersion: v1
kind: Service
metadata:
  name: product-http
  namespace: rgrpc-dev
spec:
  type: ClusterIP
  selector:
    app: product
  ports:
    - port: 9001
      protocol: TCP
      targetPort: 9001
---

# grpc service
apiVersion: v1
kind: Service
metadata:
  name: product-grpc
  namespace: rgrpc-dev
spec:
  type: ClusterIP
  selector:
    app: product
  ports:
    - port: 50051
      protocol: TCP
      targetPort: 50051
