# grpc config
grpc:
  host: ""
  port: ":50051"
  name: "user-grpc"

# http config
http:
  host: ""
  port: ":9001"
  name: "user-http"

# database config
database:
  driver: mysql # Database Drivers
  host: 192.168.1.36 # Host
  port: 3306 # Port
  username: john # Username
  password: your-passwor # Password
  database: rgrpc-user # Database
  charset: utf8mb4 # Charset
  maxIdleCons: 10 # Maximum number of connections in the idle connection pool
  maxOpenCons: 100 # Maximum number of open database connections
  logMode: info # Log level
  enableFileLogWriter: true # Whether to enable log files
  logFilename: sql.log # Log file name

# redis config
redis:
  host: 192.168.1.36
  port: ":6379"
  username: "default"
  password: your-password
  database: 0
  dial_timeout: 10s
  read_timeout: 10s
  write_timeout: 10s
  pool_timeout: 10s
  pool_size: 10

# logger
logger:
  path: "./storage/grpc.log"
  maxSize: 1024 # MB
  localTime: true

# client
client:
  authHost: auth-grpc
  authPort: ":50051"