// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"permissionservice/config"
	"permissionservice/genproto/v1"
	"permissionservice/service"
)

// Injectors from wire.go:

// InitServer Inject service's component
func InitServer(conf *config.Config) (v1.PermissionServiceServer, error) {
	permissionServiceServer := service.NewServer(conf)
	return permissionServiceServer, nil
}
