// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"orderservice/config"
	"orderservice/service/v1/client"
	"orderservice/service/v1/server"
)

// Injectors from wire.go:

func InitServer(cfg string) (*Server, error) {
	configConfig := config.NewConfig(cfg)
	group := NewRunGroup()
	logger := NewLogger()
	server := NewHttpServer(configConfig)
	db := NewDB(configConfig)
	repository := serverV1.NewRepository(db)
	orderServiceClient, err := clientV1.NewOrderClient(configConfig)
	if err != nil {
		return nil, err
	}
	authServiceClient, err := clientV1.NewAuthClient(configConfig)
	if err != nil {
		return nil, err
	}
	productServiceClient, err := clientV1.NewProductClient(configConfig)
	if err != nil {
		return nil, err
	}
	orderServiceServer := serverV1.NewServer(logger, configConfig, repository, orderServiceClient, authServiceClient, productServiceClient)
	grpcServer := NewGrpcServer(logger, orderServiceServer)
	serverServer := NewServer(configConfig, group, logger, server, grpcServer, db)
	return serverServer, nil
}
