# service
apiVersion: v1
kind: Service
metadata:
  name: order-http
  namespace: rgrpc-dev
spec:
  type: ClusterIP
  selector:
    app: order
  ports:
    - port: 9001
      protocol: TCP
      targetPort: 9001
---
# service
apiVersion: v1
kind: Service
metadata:
  name: order-grpc
  namespace: rgrpc-dev
spec:
  type: ClusterIP
  selector:
    app: order
  ports:
    - port: 50051
      protocol: TCP
      targetPort: 50051
