# grpc 服务配置
grpc:
  host: ""
  port: ":50052"
  name: "order-grpc"

# http 服务配置
http:
  host: ""
  port: ":9002"
  name: "order-http"

# database 数据库配置
database:
  mysql:
    host: 172.16.222.36 # 数据库地址
    port: 3306 # 数据库端口
    username: root # 账号
    password: 1100 # 密码
    database: rgrpc-order # 数据库
    charset: utf8mb4 # 编码
    maxIdleCons: 10 # 连接池最小数量
    maxOpenCons: 100 # 连接池最大数量
    logMode: info # 日志等级
    enableFileLogWriter: true # 是否开启日志文件写入
    logFilename: sql.log # 文件名称

# client 客户端配置
client:
  # product 产品服务客户端
  productHost: product
  productPort: ":50051"


# tracer
trace:
  tracerName: "order-service-tracer"
  serviceName: "order-service"
  endPoint: "otel-collector.otel:4317"