// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"userservice/config"
	"userservice/genproto/go/v1"
	"userservice/pkg"
	"userservice/service"
)

// Injectors from wire.go:

// InitServer Inject service's component
func InitServer(conf *config.Config) (userV1.UserServiceServer, error) {
	db := pkg.NewDB(conf)
	client := pkg.NewRedis(conf)
	authServiceClient, err := service.NewAuthClient(conf)
	if err != nil {
		return nil, err
	}
	repository := service.NewRepository(db, client, authServiceClient)
	userServiceClient, err := service.NewClient(conf)
	if err != nil {
		return nil, err
	}
	userServiceServer := service.NewServer(repository, userServiceClient)
	return userServiceServer, nil
}
